# Generated by Django 5.1.6 on 2025-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سایت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='logo/%Y/%m/%d')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('x', models.URLField(blank=True, null=True, verbose_name='لینک ایکس')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='لینک یوتیوب')),
                ('github', models.URLField(blank=True, null=True, verbose_name='لینک گیت هاب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
                'ordering': ['-created_at'],
            },
        ),
    ]
