# Generated by Django 5.1.6 on 2025-03-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='Skill',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='مهارت ها'),
        ),
    ]
