# Generated by Django 5.1.6 on 2025-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0002_siteinfo_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='Skill',
            field=models.TextField(blank=True, null=True, verbose_name='مهارت ها'),
        ),
    ]
