# Generated by Django 5.1.6 on 2025-03-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0003_alter_siteinfo_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='Skill',
        ),
    ]
