# Generated by Django 5.1.6 on 2025-02-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
