# Generated by Django 5.1.6 on 2025-03-21 11:21

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
