# Generated by Django 5.1.6 on 2025-03-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='image',
            new_name='image_one',
        ),
        migrations.AddField(
            model_name='resume',
            name='image_three',
            field=models.ImageField(blank=True, upload_to='resume/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='resume',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='resume/%Y/%m/%d'),
        ),
    ]
