# Generated by Django 5.1.6 on 2025-03-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_image_resume_image_one_resume_image_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
