# Generated by Django 5.1.6 on 2025-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryresume',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='categoryresume',
            name='description',
        ),
        migrations.AddField(
            model_name='categoryresume',
            name='slug',
            field=models.SlugField(default='your_default_value', unique=True),
        ),
    ]
