# Generated by Django 5.1.6 on 2025-03-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_categoryresume_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='zip_file',
        ),
    ]
