# Generated by Django 5.1.6 on 2025-03-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_resume_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='your_default_value', unique=True),
        ),
    ]
