# Generated by Django 5.1.6 on 2025-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_resume_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skill',
            field=models.TextField(blank=True, null=True, verbose_name='مهارت ها'),
        ),
    ]
