# Generated by Django 5.1.6 on 2025-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_skill_remove_resume_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='resume.skill'),
        ),
    ]
