# Generated by Django 5.1.6 on 2025-03-24 02:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_alter_resume_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='image_two',
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
